---
- name: install sqm-scripts package
  opkg:
    name: sqm-scripts
    state: present
    update_cache: yes

- name: install luci-app-sqm package
  opkg:
    name: luci-app-sqm
    state: present
  when: luci_support == True

- name: set queue
  uci:
    command: set_object
    config: sqm
    type: queue
    section: '{{item.key}}'
    values:
      enabled: "{{item.value.enabled | default(None) | int(None)}}"
      upload: "{{item.value.upload}}"
      download: "{{item.value.download}}"
      qdisc: "{{item.value.qdisc}}"
      qdisc_advanced: "{{item.value.qdisc_advanced | default(None) | int(None)}}"
      qdisc_really_really_advanced: "{{item.value.qdisc_really_really_advanced | default(None) | int(None)}}"
      script: "{{item.value.script}}"
      linklayer: "{{item.value.linklayer}}"
      debug_logging: "{{item.value.debug_logging | default(None) | int(None)}}"
      verbosity: "{{item.value.verbosity}}"
  with_dict: "{{queues}}"
  notify:
    - uci commit sqm
    - reload sqm
