---
- name: set queue enabled
  uci:
    command: set
    config: "sqm"
    section: "{{interface}}"
    type: "queue"
    option: "enabled"
    value: "{{enabled | int}}"
  notify:
    - uci commit sqm
    - reload sqm

- name: set queue upload
  uci:
    command: set
    config: "sqm"
    section: "{{interface}}"
    type: "queue"
    option: "upload"
    value: "{{upload}}"
  notify:
    - uci commit sqm
    - reload sqm

- name: set queue download
  uci:
    command: set
    config: "sqm"
    section: "{{interface}}"
    type: "queue"
    option: "download"
    value: "{{download}}"
  notify:
    - uci commit sqm
    - reload sqm

- name: set queue qdisc
  uci:
    command: set
    config: "sqm"
    section: "{{interface}}"
    type: "queue"
    option: "qdisc"
    value: "{{qdisc}}"
  notify:
    - uci commit sqm
    - reload sqm

- name: set queue qdisc_advanced
  uci:
    command: set
    config: "sqm"
    section: "{{interface}}"
    type: "queue"
    option: "qdisc_advanced"
    value: 1
  when: qdisc_advanced == True
  notify:
    - uci commit sqm
    - reload sqm

- name: remove queue qdisc_advanced
  uci:
    command: delete
    config: "sqm"
    section: "{{interface}}"
    option: "qdisc_advanced"
  when: qdisc_advanced != True
  notify:
    - uci commit sqm
    - reload sqm

- name: set queue qdisc_really_really_advanced
  uci:
    command: set
    config: "sqm"
    section: "{{interface}}"
    type: "queue"
    option: "qdisc_really_really_advanced"
    value: 1
  when: qdisc_really_really_advanced == True
  notify:
    - uci commit sqm
    - reload sqm

- name: remove queue qdisc_really_really_advanced
  uci:
    command: delete
    config: "sqm"
    section: "{{interface}}"
    option: "qdisc_really_really_advanced"
  when: qdisc_really_really_advanced != True
  notify:
    - uci commit sqm
    - reload sqm

- name: set queue script
  uci:
    command: set
    config: "sqm"
    section: "{{interface}}"
    type: "queue"
    option: "script"
    value: "{{script}}"
  notify:
    - uci commit sqm
    - reload sqm

- name: set queue linklayer
  uci:
    command: set
    config: "sqm"
    section: "{{interface}}"
    type: "queue"
    option: "linklayer"
    value: "{{linklayer}}"
  notify:
    - uci commit sqm
    - reload sqm

- name: set queue debug_logging
  uci:
    command: set
    config: "sqm"
    section: "{{interface}}"
    type: "queue"
    option: "debug_logging"
    value: "{{debug_logging | int}}"
  notify:
    - uci commit sqm
    - reload sqm

- name: set queue verbosity
  uci:
    command: set
    config: "sqm"
    section: "{{interface}}"
    type: "queue"
    option: "verbosity"
    value: "{{verbosity}}"
  notify:
    - uci commit sqm
    - reload sqm
